[core]
reloadable = true
order = 0

[package]
version = "1.0.1"
category = "Simulation"
title = "brownbot_ext_example"
description = "An isaac lab policy is imported into isaac sim for picking a cube "
authors = ["NVIDIA"]
repository = ""
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"isaacsim.gui.components" = {}
"isaacsim.core.api" = {}

[[python.module]]
name = "brownbot_ext_example_python"