# Use the Isaac Sim image as base
FROM nvcr.io/nvidia/isaac-sim:4.5.0

# Set default RUN shell to bash
# SHELL ["/bin/bash", "-c"]

# Set the default entrypoint to bash
#ENTRYPOINT ["bash"]
ENTRYPOINT ["/bin/bash"]

# Keep container running
#CMD ["tail", "-f", "/dev/null"]